### ISSUE TITLE
!steamstatus is broken

### ISSUE THREAD

**Issue by Tele42** [SteamLUG/steamlug-bot#10]
This broke at some point in the past.

**Comment by johndrinkwater** [comment]
How is it failing, does it output ‘Sorry, currently unavailable.’ or does it not get that far?

**Comment by johndrinkwater** [comment]
Maybe `steamlug-bot_settings.php` was updated by git and it reverted to this → 

```
$GLOBALS['steamstatus'] = 'SECRET';
```

**Comment by Tele42** [comment]
Thanks for pointing that config out. The current value points to a dead / gone domain.

**Comment by Tele42** [comment]
The config is fixed.
