### ISSUE TITLE
ping timeout

### ISSUE THREAD

**Issue by Tele42** [SteamLUG/steamlug-bot#5]
steamlug-bot does not detect ping timeout and take action

Expected result:
steamlug-bot should try to reconnect quickly, and take progressively longer between tries until it reaches a reasonable max retry time.

**Comment by EndeavourAccuracy** [comment]
It *does* reconnect.

    do {
    Connect(); 	
    while (feof ($GLOBALS['socket']) == FALSE)
    {
    }
    } while (1);

Function feof() returns TRUE for a socket timeout. However, if the server is crap the bot eventually gives up entirely; see the Connect() function. That's why I didn't use server rotation (chat.freenode.net) but hardcoded $GLOBALS['irc_host'] to a proper server (130.239.18.172, which if I'm not mistaken is leguin.freenode.net).

What problem exactly did you run into? If you just keep it running, it should auto-reconnect.
You could remove exit() [here](https://github.com/SteamLUG/steamlug-bot/blob/master/steamlug-bot.php#L28), if it dropped a "Could not connect!" error.

**Comment by Tele42** [comment]
Looks like this was not enough, if the bot gets disconnected, it doesn't hit this retry loop.

**Comment by Tele42** [comment]
could adding ```fclose ($GLOBALS['socket']);``` after the ```while (feof ($GLOBALS['socket']) == FALSE)``` loop help?
```
[ WAIT ] :asimov.freenode.net CAP steamlug-bot ACK :identify-msg 
[ WARN ] Unknown +/- status: :asimov.freenode.net NOTICE #steamlug :[freenode-info] channel flooding and no channel staff around to help? Please check with freenode support: http://freenode.net/faq.shtml#gettinghelp
[ INFO ] :services. 328 steamlug-bot #steamlug :http://steamlug.org
[ INFO ] ERROR :Closing Link: unaffiliated/kisak/bot/steamlug-bot (Ping timeout: 255 seconds)
[ WAIT ] :rajaniemi.freenode.net CAP steamlug-bot ACK :identify-msg 
[ INFO ] :services. 328 steamlug-bot #steamlug :http://steamlug.org
```
no channel rejoin, bot can not be /msg'd.

**Comment by EndeavourAccuracy** [comment]
Yes, try adding that `fclose`. And also add this there:

    $GLOBALS['socket'] = FALSE;

However, the last two lines of the bot output you included in your recent post show the bot already reconnects, in this case after a timeout. And in the code it already sets `$iJoined = 0;` before it (re)calls Connect(), plus it got the ACK for the cloak, so going by just the output I would've said it rejoined the channel.

You could temporarily `print ($sString . "\n");` in `function Write ($sString)` to see everything it's sending to the socket. Perhaps with `if (substr ($sString, 0, 5) != 'PONG ') { ... }`. However, it's easier to access log.php to see what it's been doing.

**Comment by Tele42** [comment]
Okay ... on to the next hypothesis; I think what I'm reading says the bot is checking how long it's been since the last time it saw a server ping, so if the connection is silently dropped, then the bot can be sitting waiting with an open socket for server messages that are not going to come.
Something like http://stackoverflow.com/questions/6853071/python-check-if-irc-connection-is-lost-ping-pong

**Comment by EndeavourAccuracy** [comment]
Unfortunately, I currently lack the time to look into this.
But I see you already found a good solution, I hope it will do what we think it does.

**Comment by Tele42** [comment]
Since the bot was reconnecting sometimes during the recent DDoS, the second part probably is fine without being addressed.
